version: '3'
services:
  demo-native:
    #image: "quarkus/code-with-quarkus-jvm"
    image: "quarkus/code-with-quarkus"
    cpus: 0.5
    ports:
      - 8080:8080

  demo-db:
    image: "postgres:12"
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: password
      POSTGRES_DB: demo
    ports:
      - 5432:5432
    networks:
      - demo
    volumes:
      - demo-data:/var/lib/postgresql/data

networks:
  demo:
    driver: bridge

volumes:
  demo-data: